# https://developers.home-assistant.io/docs/add-ons/configuration#add-on-config
name: BorgBackup add-on
version: "0.0.1"
slug: borg_backup
description: Installs and manages BorgBackup
url: "https://github.com/greenmoss/hassio-addons/tree/main/borg_backup"
arch:
  - armhf
  - armv7
  - aarch64
  - amd64
  - i386
init: false
map:
  - share:rw
options:
  message: "Hello world..."
schema:
  message: "str?"
#image: "ghcr.io/greenmoss/{arch}-addon-borg_backup"

